### ISSUE TITLE
[BUG] Long respring times

### ISSUE THREAD

**Issue by koiseka** [Muirey03/CentaurIssueReporting#3]
**Describe the bug**
With Centaur it's taking forever to respring here's the respring times:

Centaur: 20secs
Centaur + other tweaks: 2mins
Other tweaks without Centaur: 12secs
No tweaks: 8secs

**To Reproduce**

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue occurs every time and you are able to reliably reproduce it
 - [X] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [X] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?

**Expected behavior**
For it to not take so long to respring with Centaur

**Device (please complete the following information):**
 - Device: [iPhone 6s]
 - iOS Version: [iOS12.1]

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
We're any crash reports generated?

**Comment by koiseka** [comment]
Nope, no crash reports in Cr4shed.

**Comment by Muirey03** [comment]
What about CrashReporter?

**Comment by koiseka** [comment]
Nope :/

**Comment by tryaink** [comment]
Same bug
Respring loop when i installed this tweak

iPhone XR iOS 12.1 Chimera

Crash reporter and Cr4shed not detected 

Please fix this bug

I was buy
Nothing use crack

**Comment by koiseka** [comment]
So can this be fixed or should I request for a refund?

**Comment by tryaink** [comment]
I will wait for Fix update

**Comment by Muirey03** [comment]
@tryaink that is a different bug that I have fixed in v.1.0.1

**Comment by tryaink** [comment]
Okay
I will test for new update

**Comment by tryaink** [comment]
@Muirey 
Cannot find update version on Sileo

**Comment by Muirey03** [comment]
@tryaink that' because it isn't available yet

**Comment by HydriDev** [comment]
v.1.0.1 fixed long respring times for me (resprings are now 8secs) but I still can't tap on app icons to show specific notifications

**Comment by koiseka** [comment]
v1.0.1 fixed long respring times (8secs to respring now)

**Comment by Muirey03** [comment]
Perfect, I'll close this issue now then
